### ISSUE TITLE
Managing master + main branches

### ISSUE THREAD

**Issue by jmandel** [hl7au/au-fhir-core#1]
Hi there! Quick note that the FHIR CI pipeline now supports default branches of `master` as well as `main`. When you commit to this repo, your default branch will then be hosted at https://build.fhir.org/ig/hl7au/au-fhir-core .

It looks like you are currently maintaining both `master` and `main` branches, which can be confusing to keep straight. You may want to consider picking just one of these, making it your default branch at https://github.com/hl7au/au-fhir-core/settings, and getting rid of the other one.

https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Publisher.20using.20master.20OR.20main for details.

Please let me know if you have any questions.

**Comment by dt-r** [comment]
Thanks @jmandel, we will be go back to only master shortly and remove main - the main was a temp workaround for something else.
