### ISSUE TITLE
Condition search by patient+onset-date formatting issues

### ISSUE THREAD

**Issue by StephThaoOng** [hl7au/au-fhir-core#204]
**Condition Profile** formatting issues

- [ ] Optional Search Parameters section:
Last combined search: _SHOULD support searching using the combination of the patient and onset-date search parameters_ is currently a sub-point under another 'search'. Seems like it should be numbered 3 in this section's list.

- [ ] patient+onset-date search in the table under section 14.8.1.5 seems to be missing the requirements description as shown in image below
![image](https://github.com/hl7au/au-fhir-core/assets/36804832/e7fce947-ad46-4ba1-b654-2eb9e2b542b0)

Issue noted in version: 0.4.0-ci-build

**Comment by dt-r** [comment]
@StephThaoOng if you mean to raise a change on AU Core then please raise as a JIRA.

**Comment by StephThaoOng** [comment]
Close issue - to be raised as a Jira issue.
