### ISSUE TITLE
HealthCare Service missing

### ISSUE THREAD

**Issue by jakubsielewicz** [hl7au/au-fhir-core#253]
Given that we have included Organization, PractitionerRole and Location, is there a specific reason we have omitted HealthcareService from AU Core. Inclusion of this profile would make extension and derivation a lot cleaner to other IGs (i.e. PD).

**Comment by dt-r** [comment]
@jakubsielewicz, specification feedback on AU Core can be raised using http://hl7.org/fhir-issues
