### ISSUE TITLE
Develop guidance on use of Provider identifiers in Australia

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#55]
Outcome from [2023-09-28 AU Core TDG Agenda/Minutes](https://confluence.hl7.org/pages/viewpage.action?pageId=184920587). TDG to work on developing guidance on the use of different identifiers and when in Australia to include in AU Core.

Guidance should include use of official name.

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43845](https://jira.hl7.org/browse/FHIR-43845).

Questions on this profile or how to use the Practitioner resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
