### ISSUE TITLE
Clarify how Condition.code and Condition.bodySite work together

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#64]
We should clarify how Condition.code and Condition.bodySite work together i.e bodySite is redundant as body site pre-coordinated in Condition.code or qualifies Condition.code as body site is not defined in code.

_Originally posted by @brettesler-ext in https://github.com/hl7au/au-fhir-core/discussions/52#discussioncomment-7297725_

**Comment by dt-r** [comment]
confluence

**Comment by dt-r** [comment]
next meeting

**Comment by dt-r** [comment]
See .... for possible use of terminology

**Comment by dt-r** [comment]
Discussion on Condition code, body site, and laterality held 6/11/2023. 

- FHIR Resources this discussion may apply to are: Condition, Procedure, ServiceRequest
- Discussion on applicable 'qualifiers' of a body site discussed the body site qualifier set and confirmed only laterality relevant
- Cases defined as:
   - CASE 1: System has single primary field e.g. condition code and/or text, order code and/or text, procedure code and/or text
   - CASE 2: System has primary field (condition code and/or text) and laterality field
   - CASE 3: System has primary field (condition code and/or text), laterality field, bodysite field
   - CASE 4: System has primary field (condition code and/or text) and bodysite where bodysite may be more specific than is part of the primary field
- relevant national and international specifications (US Core, IPS, IPA) do not explicitly support bodySite element in any resource profile

**Comment by brettesler-ext** [comment]
Proposal added as ticket https://jira.hl7.org/browse/FHIR-44712 issue - issue closed here.
