### ISSUE TITLE
How to do 'free text' medical history i.e. are these always Condition?

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#65]
We should have an explicit position on how to do 'free text' medical history i.e. are these always Condition?

_Originally posted by @brettesler-ext in https://github.com/hl7au/au-fhir-core/discussions/52#discussioncomment-7297710_

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43846](https://jira.hl7.org/browse/FHIR-43846).

Questions and feedback can be provided in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
