### ISSUE TITLE
Improve text of au-core-cond-02

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#67]
The text should be improved in au-core-cond-02: If a coded body site is provided, at least one code shall be from SNOMED CT
Consider
au-core-cond-02: If a coded body site is provided, at least one **of it's codes** shall be from SNOMED CT

That makes it clear that each instance of bodySite is tested separately. That a SNOMED CT code on one bodySite does not mean that all of the other bodySites can use codes without SNOMED CT translations.

_Originally posted by @RichardTON in https://github.com/hl7au/au-fhir-core/discussions/52#discussioncomment-7399507_

**Comment by dbojicic** [comment]
@RichardTON, after some consideration it was decided to put this invariant wording through the Connectathon test in March 2024. The outcome may be no change, implement your suggestion or something completely different, depending on the community agreement. 
To make sure we don't lose track of it, agreed with @brettesler-ext to create a temporary page that collects items for attention at the next Connectathon, see https://confluence.hl7.org/display/HA/AU+Core+Track+-+2024-03.

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43848](https://jira.hl7.org/browse/FHIR-43848).

Questions on this profile or how to use the Condition resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia

**Comment by RichardTON** [comment]
OFFICIAL

Hi Dusi

I created and shared a Jira filter to show the HL7 AU FHIR issues. Something like it will be useful. https://jira.hl7.org/issues/?filter=21324

Kind regards

Richard Townley-O'Neill - Lead Clinical Information Modeller - Digital Health Architecture - Digital Solutions Division
Phone: +61 7 3023 8524<tel:+61730238524> Email: ***@***.******@***.***> Web: www.digitalhealth.gov.au<https://www.digitalhealth.gov.au/>



OFFICIAL

**Comment by dbojicic** [comment]
Hi @RichardTON, all individual GitHub tickets are linked to their corresponding JIRA tickets. [au-fhir-core README.md](https://github.com/hl7au/au-fhir-core) has been updated to link to [Jira issue tracker](https://jira.hl7.org/browse/FHIR-43719?filter=21312) with a similar filter to show all open HL7 AU FHIR issues.
