### ISSUE TITLE
How to support diagnosis type e.g. Comorbidity, Complication

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#68]
From Queensland Health:

...

2. If we needed to capture a `diagnosis type` (A qualifier to indicate the type of diagnosis eg. Comorbidity, Complication) - where would we capture this in the AU Core Condition profile?

...
_Originally posted by @reubendaniels in https://github.com/hl7au/au-fhir-core/discussions/52#discussioncomment-7309999_

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43847](https://jira.hl7.org/browse/FHIR-43847).

Questions on this profile or how to use the Condition resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia.
