### ISSUE TITLE
AU Core specific set for Condition.code suggested

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#69]
From Queensland Health:

...

3. Code for the Condition/Problem or Diagnosis is currently extensibly bound to the [https://healthterminologies.gov.au/fhir/ValueSet/clinical-condition-1](https://healthterminologies.gov.au/fhir/ValueSet/clinical-condition-1) NCTS value set. It is suggested that an AU Core specific value set is defined for this binding for the following reasons:

- An AU Core value set can be maintained/curated through the HL7 Australia standards development process independent of the NCTS. Note: an AU Core value set may still be published in the NCTS if HL7 Australia and the NCTS operator are open to this.
- The NCTS value set is itself defined as including all the member of the Problem/Diagnosis SNOMED CT-AU reference set. While many of these concepts are likely to be appropriate for this binding, the reference set may not have been developed with the same goals as AU Core. Further, changes to the reference set (e.g. retirement of member concepts by the Australian NRC or SNOMED International) would impact this value set's expansion and thus the binding.

_Originally posted by @reubendaniels in https://github.com/hl7au/au-fhir-core/discussions/52#discussioncomment-7309999_

**Comment by dt-r** [comment]
@reubendaniels is this a governance question or is this driven by content?

Current practice coming out of agreements from the old PA Work Group several years ago between Agency and the work groups is that where HL7 AU value sets are SNOMED CT or LOINC that they are authored and published in the NCTS as NCTS sets.

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43849](https://jira.hl7.org/browse/FHIR-43849).

Questions on this profile or how to use the Condition resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
