### ISSUE TITLE
Remove the mandatory requirement to support _revinclude of provenance

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#70]
I suggest removing the mandatory requirement to support _revinclude of provenance until we at least have a profile for it.

_Originally posted by @heathfrankel in https://github.com/hl7au/au-fhir-core/discussions/37#discussioncomment-7076260 and https://github.com/hl7au/au-fhir-core/discussions/38#discussioncomment-7076291 and https://github.com/hl7au/au-fhir-core/discussions/39#discussioncomment-7076252_

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43850](https://jira.hl7.org/browse/FHIR-43850).

Questions can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
