### ISSUE TITLE
The definition of Must Support in AU Core should be updated to support broader adoption.

### ISSUE THREAD

**Issue by reubendaniels** [hl7au/au-fhir-core#75]
As of this writing, Must Support in AU Core ([here](https://build.fhir.org/ig/hl7au/au-fhir-core/must-support.html)) is defined in terms of requesters (client systems) and responders (server systems).

Accordingly, it is unclear how Must Support is to be interpreted by implementers seeking to adopt AU Core in contexts outside of a client/server architecture e.g. those seeking to implement under the [Profile Only](https://build.fhir.org/ig/hl7au/au-fhir-core/general-requirements.html#profile-only-support) model.

Further, under the current Must Support definition, the implicit assumptions that

1. requesters are necessarily always receiving/processing FHIR data from a responder (server system)
2. responders are necessarily always creating/sending  FHIR data to a requester (client system)

may not necessarily be true e.g. some requesters (clients)may create FHIR resources to be sent to the server, and the responders (servers) may process incoming FHIR resources and not send FHIR resources as a response.

Accordingly, it is suggested that the description of Must Support in AU Core be updated to address the above issues.

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43852](https://jira.hl7.org/browse/FHIR-43852).

Questions can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
