### ISSUE TITLE
Change Capability Statement title to align with Application roles used in Conforfmance/Must Support 

### ISSUE THREAD

**Issue by heathfrankel** [hl7au/au-fhir-core#76]
The Conformance Must Support page uses application role names of Responder and Requester. The Capability Statements should use these same role names to help alignment of these Must Support requirements to the associated Capability Statement.

I would also suggest that we include REST in this title to make it clear that this is a REST API Requester/responder, not a document or messaging actor.

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43853](https://jira.hl7.org/browse/FHIR-43853).
