### ISSUE TITLE
AU Core PractitionerRole: Remove must support from PractitionerRole.location

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#78]
I think we are moving to the position that PractitionerRole.location isn't core of the core and we want to be silent on in AU Core. We didn't quite finish that discussion previously and should look at this, maybe in the October 19 meeting.

_Originally posted by @dt-r in https://github.com/hl7au/au-fhir-core/discussions/38#discussioncomment-7153566_

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43841](https://jira.hl7.org/browse/FHIR-43841).

Questions on this profile or how to use the Encounter resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
