### ISSUE TITLE
If Identifier not mandatory can we add an additional conformance requirement that at least one of Organisation, Healthcare Service, or Location(maybe) mandatory

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#79]
If Identifier is not made mandatory can we add an additional conformance requirement that at least one of Organisation, Healthcare Service, or Location(maybe) mandatory

_Originally posted by @dylan-jf7 in https://github.com/hl7au/au-fhir-core/discussions/38#discussioncomment-7129822_

**Comment by dt-r** [comment]
Agreed. This already exists for Organization, Location, HealthcareService. For profile of an entity type resource (Patient, Organization, etc.) if identifier isn't mandatory then we need a constraint that says that one of the accepted identifying elements need to be supplied e.g. name or identifier or ...

For PractitionerRole my preference is:
`The practitioner role shall at least have a valid identifier or practitioner or code`

We should discuss this. Maybe in the October 19 zoom call.

_Originally posted by @dt-r in https://github.com/hl7au/au-fhir-core/discussions/38#discussioncomment-7153561_

**Comment by dbojicic** [comment]
Just a comment on the statement above - this already exists for Location. Both Organization and HealthcareService mandate `name`. 
AU Core mandates PractitionerRole.practitioner. Should practitioner be made optional and a constraint added to mandate one of the identifying element or a link to an entity (Practitioner, Organization)?

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43855](https://jira.hl7.org/browse/FHIR-43855).

Questions on this profile or how to use the Encounter resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
