### ISSUE TITLE
AU Core PractitioenrRole: search parameter changes

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#80]
Mandatory Search parameter for practitioner by reference I suspect is unuseful, the chained practitioner.identifier would be more likely.
If HPI-I is removed from the PractitionerRole, then it should be removed from the identifier search parameter.
Providing a code only in an identifier search parameter is ambiguous. If allowed, I would suggest stating a single (or explicit list) type of identifier that will be used in the search.
a chained organization.identifier may be better or additional search parameter than the organization reference.

_Originally posted by @heathfrankel in https://github.com/hl7au/au-fhir-core/discussions/38#discussioncomment-7076291_

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43839](https://jira.hl7.org/browse/FHIR-43839).

Questions on this profile or how to use the Encounter resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
