### ISSUE TITLE
Should add to AU Core description of scenarios where the Organization resource should be (and should not be) used

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#81]
I think there is some value in describing the scenarios where the Organization resource should be (and should not be) used, perhaps as use cases. Specifically, how it relates to HealthcareService and Location resources and organizational structures. For example, how does Organization get used to represent primary and community care organizations with multiple clinics, shared facilities and outreach locations. Similarly how are hospital organizations represented with multiple multiple campuses, buildings departments and outpatient clinics?
Some best practice and practical examples would be beneficial to ensure implementation consistency.

_Originally posted by @heathfrankel in https://github.com/hl7au/au-fhir-core/discussions/39#discussioncomment-7076223_

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43856](https://jira.hl7.org/browse/FHIR-43856).

Questions on this profile or how to use the Organization resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
