### ISSUE TITLE
AU Core Patient: Usage scenarios be more specific as this will provide better guidance

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#83]
Can the Usage scenarios be more specific as this will provide better guidance around the constraints being applied in the profile. For example:

- Synchronising Patient Administration System patient records with departmental or financial systems
- Support SMART Apps such as Smart Forms in Primary Care and Hospital Systems
- Support primary care and aged care quality indicator data extracts (enabling a client to use raw data to produce QIs)
- Diagnostic requests, specialist referrals and aged care transfers
- Hospital theatre bookings

I am also have a concern that we are trying to conform with international and US profiles, which is making the minimum requirements for AU vendors unnecessary, such as the must support for _revinclude Provenance, _id (the read request is more commonly used for this) in searches and the various combinations (I guess they are should, but then from a compliance perspective this is meaningless - wont need to be implemented). A mandatory identifier may also be problematic for scenarios with foreign patients without IHI/MCN (yes I know missing data extensions can be added, but this could be challenging for new implementers).

On the other hand, we need to consider that a AU Core Responder may be implementing using a façade pattern and not have generic search capabilities, in this case it may be useful to indicate exactly which identifier types that shall be supported in search requests, e.g. IHI and MCN, but not DVA or MRN.

_Originally posted by @heathfrankel in https://github.com/hl7au/au-fhir-core/discussions/36#discussioncomment-7075695_

**Comment by dbojicic** [comment]
Re comment on must-support for Provenance in US Core posted by @grahamegrieve in [#36 (comment)](https://github.com/hl7au/au-fhir-core/discussions/36#discussioncomment-7076294). 

US Core supports as a SHALL for the following US Core resources types
- AllergyIntolerance 
- CarePlan                  
- CareTeam
- Condition
- Coverage
- Device
- DiagnosticReport
- DocumentReference
- Encounter
- Goal
- Immunization
- MedicationDispense
- MedicationRequest
- Observation
- Patient
- Procedure
- QuestionnaireResponse
- RelatedPerson
- ServiceRequest

1. searching using a combination of the _patient_ and __revinclude_Provenance search parameters
2. searching using a combination of the __id_ and the __revinclude_ Provenance  search parameters

See [US Core Provenance]( https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-provenance.html).

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43857](https://jira.hl7.org/browse/FHIR-43857).

Questions on this profile or how to use the Patient resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
