### ISSUE TITLE
AU Core Encounter: Encounter.period should be optional

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#85]
Why have we made period mandatory whereas US Core hasn't? This will limit the use of core encounter when the period isn't known.

_Originally posted by @gonatf in #30 and moved by @dbojicic to https://github.com/hl7au/au-fhir-core/discussions/62#discussioncomment-7675064_

Responses to https://github.com/hl7au/au-fhir-core/discussions/62#discussioncomment-7675064

> [dt-r](https://github.com/dt-r) [on Nov 30, 2023](https://github.com/hl7au/au-fhir-core/discussions/62#discussioncomment-7711851)
One of the main sources for the currently baseline of AU Core for community engagement comes from event-driven patient summary implementation guides like Discharge Summary. I expect that to be the source of this cardinality. 
Can you describe your use of encounter information and the need to support encounter but without an encounter period?

> [gonatf](https://github.com/gonatf) [on Nov 30, 2023](https://github.com/hl7au/au-fhir-core/discussions/62#discussioncomment-7711905)
Given both start and end are optional in period, I guess including a period with no start/end makes it all a bit strange to be mandatory. My use case is things like creating a request within an encounter that hasn't ended or not knowing the when a previous encounter occurred but knwoing something that resulted from it or is linked to it.

**Comment by dt-r** [comment]
For TDG consideration - Encounter.period changed from 1..1 to be 0..1.

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available.

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43832](https://jira.hl7.org/browse/FHIR-43832).

Questions on this profile or how to use the Encounter resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
