### ISSUE TITLE
AU Core  - discrepancy in the Downloadable copy (Excel format)

### ISSUE THREAD

**Issue by melholden** [hl7au/au-fhir-core#87]
From https://build.fhir.org/ig/hl7au/au-fhir-core/downloads.html I clicked on Downloadable Copy:
 ![image](https://github.com/hl7au/au-fhir-core/assets/151097662/c3c673d3-71c9-4d9c-966c-b0ad77c1a6f5)

This downloads the full-ig zip folder. I then opened up the all-profiles Excel file:
![image](https://github.com/hl7au/au-fhir-core/assets/151097662/c5d6ce50-2b32-4002-bafe-4b8ac40b864a)

There are 4x values in the file:
![image](https://github.com/hl7au/au-fhir-core/assets/151097662/4325e64a-deba-4c4c-94d5-d94286777273)

however the URL  [http://hl7.org/fhir/ValueSet/allergyintolerance-verification|4.0.1](http://hl7.org/fhir/ValueSet/allergyintolerance-verification%7C4.0.1) is listed as the binding valueset to use. When I click on this URL, it opens up to the International Release 5 webpage https://hl7.org/fhir/valueset-allergyintolerance-verification.html which has 5x values (an additional value of “presumed”): 
![image](https://github.com/hl7au/au-fhir-core/assets/151097662/99c0ba60-67bc-4ac3-9d0a-a946b4b3d085)

Also, when I navigate to the AU CORE https://build.fhir.org/ig/hl7au/au-fhir-core/ and open up the page for AllergyIntolerance Resource https://build.fhir.org/ig/hl7au/au-fhir-core/StructureDefinition-au-core-allergyintolerance.html, it has 4x values:
 
When I click on the URL, it opens up to the International Release 4 webpage https://hl7.org/fhir/R4/valueset-allergyintolerance-verification.html which contains 4x values: 
![image](https://github.com/hl7au/au-fhir-core/assets/151097662/9950141c-0862-48c7-a5d2-2df2a136808c)

This is just one example, but generally it appears that the URLs in the all-profiles Excel file point to the International Release 5 valuesets (which are not correct because they do not always align with the valuesets and definitions as per the AU CORE IG).

Discussed this issue with Duscia. Suggest that text is added to the website to avoid any future potential issues for Implementers who may soley be using the Excel file for reference:
![image](https://github.com/hl7au/au-fhir-core/assets/151097662/f67a9680-8a32-4392-b8ab-d3503fd7e289)

**Comment by dt-r** [comment]
Hi @melholden, have you raised this with the IG Publisher tooling people that you think one of the files is incorrectly generated?

This would apply to all IGs across the world noting though that it looks like an internal file and isn't linked in the html of the Implementation Guide or in the npm package loaded on the server.

**Comment by melholden** [comment]
@dt-r I think other non-technical readers (in similar Business Analyst or Data Analyst roles) would also navigate to the Excel file if they wanted to download the entire spec from the AU Core IG. Without having a server or coding skills or being able to understand html, it's the only way in which we can view the entire meta data easily in a user-friendly format. The zip file opens up to a 'site' folder and then the excel file. A non-technical person wouldn't know how to do it any other way (or how to host it???), we always just search for Excel format files:
![image](https://github.com/hl7au/au-fhir-core/assets/151097662/91938470-6b04-4b5e-8c3f-a87f9518bbc3)

I haven't messaged to IG Tooling team.

**Comment by dt-r** [comment]
So potentially adding a note that if a user is locally extracting the files the starting point is index.html and a human reader is to interact by navigating through the html pages.  We could add a warning that using the files in another manner is not recommended and may result in a user finding and reading files out of context, are internal and used for technical purposes, or that are not formally part of the IG.

**Comment by melholden** [comment]
Yes, and I think be more specific about not using the URL links in the Excel file to get the AU Core valuesets, i.e. "Do not use the URL links within the Excel file because they *may* open up to a different version of the valueset. Navigate to https://build.fhir.org/ig/hl7au/au-fhir-core/profiles-and-extensions.html and use the links to the valuesets from within the relevant profile".
For those readers who are new to FHIR, this will help re-direct them to the correct webpage. 

Suggest checking URLs in other documentation generated by the Publishing Tool to see if they open up to a different version. I don't have the technical skills to check any other formats!

**Comment by dt-r** [comment]
@dbojicic can you knock up some words to emphasize the download is a website for hosting. Warning for individuals not to use in an unintended fashion e.g. using internal files inside the downloaded site.

**Comment by brettesler-ext** [comment]
I am not sure if the columns in the excel are formally defined anywhere? The format of the element is technically a 'canonical' https://hl7.org/fhir/R4/datatypes.html#canonical which in this case an identifier referring to a versioned terminology by its ValueSet.url (unique identifier URI for the ValueSet) and the ValuesSet.version - so this format is a standard one for referring to resources so they can be searched for. Typically (but not guaranteed) url alone points to the 'current stable version' which is the latest balloted and approved version . So in this case can see this https://hl7.org/fhir/valueset-allergyintolerance-verification.json.html  is ValueSet.version="5.0.0." for the specific version in the excel file value https://hl7.org/fhir/R4/valueset-allergyintolerance-verification.json.html can be found with version 4.0.1 - typically this would be used whether published packages or via terminology service where multiple versions of terminologies can be maintained.  It is possible also to even see the 'unpublished' upcoming version https://build.fhir.org/valueset-allergyintolerance-verification.json.html where version is nominally "6.0.0-cibuild".  The versioned terminology mechanism are an important tool to handle some of the complexities of terminology management and usage of terminologies when resource profiles bind to value sets.

**Comment by dbojicic** [comment]
@brettesler-ext I have not found any formal documentation of the all-profiles Excel file. Probably the closest to defining the exact structure, including columns and their headings, is [ElementDefinition](https://www.hl7.org/fhir/R4/elementdefinition.html#ElementDefinition). The Binding Value Set representation is consistent with [ElementDefinition.binding.valueSet](https://www.hl7.org/fhir/R4/elementdefinition-definitions.html#ElementDefinition.binding.valueSet):
> Refers to the value set that identifies the set of codes the binding refers to.
   The reference may be version-specific or not (e.g. have a |[version] at the end of the canonical URL).

The IG Publisher produces a number of Excel (& csv files) "to help people do ad-hoc stuff with excel" (G.Grieve, https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Spreadsheets). US Core IG references these from the [Downloads](https://build.fhir.org/ig/HL7/US-Core/downloads.html) page, maybe AU Core should do something similar while still implementing Danielle's suggestion on including some wording to inform readers on what the files are for and how to use them?
