### ISSUE TITLE
Condition-clefttongue - change SNOMED code to '204630003 

### ISSUE THREAD

**Issue by dbojicic** [hl7au/au-fhir-core#89]
Feeback from @mjosborne1. 

I was looking at the qa output after building AU Core locally and found an error in a SNOMED code in Condition-clefttongue . The code in the IG is:
```
"system" : "http://snomed.info/sct",  
 "code" : "201480281008",
 "display" : "Cleft tongue"
```
but should be 
204630003 Cleft tongue

**Comment by dt-r** [comment]
Because the original code is not a real code? or inactive? or ?

**Comment by mjosborne1** [comment]
Does not appear to be an active or inactive SCT code

**Comment by dt-r** [comment]
OK. So it's not a real SNOMED Code.
