### ISSUE TITLE
AU Core Encounter: Remove MustSupport from Encounter.extension:encounterDescription

### ISSUE THREAD

**Issue by dt-r** [hl7au/au-fhir-core#90]
Recommend MustSupport is removed from Encounter.extension:encounterDescription in AU Core Encounter. Inclusion of this extension / similar element is premature in AU Core - need to have a discussion around how clinical notes are supported.

See [AU Core Encounter elements - What are products using?](https://confluence.hl7.org/pages/viewpage.action?pageId=204283408).

See discussion on use of the Australian extension Encounter Description: https://chat.fhir.org/#narrow/stream/179173-australia/topic/AU.20encounter-description.20extension

**Comment by dbojicic** [comment]
We are transitioning to HL7 Jira for ongoing issue tracking and resolution. Integration with HL7 Jira is now available. 

For any further updates or discussions related to this issue, please refer to corresponding [HL7 Jira issue #FHIR-43816](https://jira.hl7.org/browse/FHIR-43816). 

Questions on this profile or how to use the Encounter resource can be raised in chat.fhir.org: https://chat.fhir.org/#narrow/stream/179173-australia
